version: "3.9"

services:
  app:
    build: .

    container_name: payment-app

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/payment_db

    env_file:
      - .env

    volumes:
      - ./keys:/app/keys:ro
